---
apiVersion: v1
kind: Service
metadata:
  name: javawebappnodeport
spec:
  type: NodePort
  selector:
    app: javaapp
  ports:
  - targetPort: 8080
    port: 80
  # nodePort: Default nodeport range is 30000-32767
  #           if not mentioned, it will pick up automatically from this range