---
apiVersion: v1
kind: Pod
metadata:
  name: javawebapp
  labels:
    app: javaapp
spec:
  containers: 
  - name: jawawebappcontainer
    image: dockerhandson/java-web-app
    ports:
    - containerPort: 8080