---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: javawebappforrs
spec:
  replicas: 2
  selector:
    matchLabels:
     app: javaapp
    #matchExpression:
    # - key: app
    #   operator: In
    #   values:
    #   - javaapp
    #   - test
  template:
    metadata:
      name: javawebapppod
      labels:
        app: javaapp
    spec:
      containers:
      - containers:
        name: javawebappcontainer
        image: dockerhandson/java-web-app:1
        ports:
        - containerPort: 8080