---
apiVersion: v1
kind: ReplicationController
metadata: 
  name: javawebappforrc
  labels:
    app: javaapp
spec:
  replicas: 2 # if you not mention, bydefault it will maintain 1 replica.
  selector: 
    app: javaapp # POD label key and value
  template:
    metadata: 
      name: javawebapppod
      labels:
        app: javaapp # POB lables
    spec:
      containers:
      - name: javawebappcontainer
        image: dockerhandson/java-web-app:1
        ports:
        - containerPort: 8080
