apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvformongodb
spec:
  storageClassName: manual
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/somefolder"

    
