apiVersion: apps/v1
kind: Deplyoment
metadata: 
  name: testdeplyoment
  namespaces: somename
spec: 
  replicas: 2
  selector:
    labels:
      app: testapp 
  template: 
    metadata:
      name: podname
      labels: 
        app: testapp
    